name: Publish One Click Apps

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci && npm run publish
        env:
          GITHUB_PERSONAL_TOKEN: ${{secrets.GITHUB_PERSONAL_TOKEN}}
      - run: |
          git add -A
          git config --global user.name 'Church13'
          git config --global user.email 'church13@users.noreply.github.com'
          git commit -am "Automatic update"
          git push origin gh-pages